### ISSUE TITLE
Talker can publish "Hello World" but listener cannot receive

### ISSUE THREAD

**Issue by triplekiller** [emersonknapp/ros2-toolchain-crosscompile#2]
Thanks for your useful guide. I follow this guide and port ros2 to an aarch64 platform but the listener demo cannot receive the message from the talker demo. Any tips about this kind of issue? Thanks.

**Comment by emersonknapp** [comment]
Are you running the demo on an actual arm64 device? It is important to note that ROS2 multicast communication doesn't work in QEMU.

**Comment by triplekiller** [comment]
> Are you running the demo on an actual arm64 device? It is important to note that ROS2 multicast communication doesn't work in QEMU.

Yes. I run the demo in an actual arm64 device. And the print log of "route -n" is:

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0
224.0.0.0       0.0.0.0         240.0.0.0       U     0      0        0 eth0

I guess it means my arm64 linux kernel support multicast.

**Comment by emersonknapp** [comment]
I'm not sure exactly how to read the output of `route -n` to tell if multicast is enabled. Does that tell you that it is?

I think if `netstat -g` has an `all-systems.mcast.net` output, then it is enabled.

Other than that, I'm not that experienced with debugging network communication issues in ROS2.

**Comment by triplekiller** [comment]
route add -net 224.0.0.0 netmask 240.0.0.0 dev lo
ifconfig lo multicast

After running the above cmds, talker/listener demo works. Thanks for your help.
